/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BangumiCard: typeof import('./src/components/BangumiCard.vue')['default']
    DayCard: typeof import('./src/components/DayCard.vue')['default']
    NPopover: typeof import('naive-ui')['NPopover']
    PlatformItem: typeof import('./src/components/PlatformItem.vue')['default']
    PlatformMenu: typeof import('./src/components/PlatformMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineContent: typeof import('./src/components/TimelineContent.vue')['default']
    TimelineItem: typeof import('./src/components/TimelineItem.vue')['default']
    TimelineMenu: typeof import('./src/components/TimelineMenu.vue')['default']
  }
}
